-- Run once in the Supabase SQL Editor before starting the backend.
-- The service key used by the backend bypasses RLS; do not expose it to the frontend.
create extension if not exists vector with schema extensions;

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  filename text not null,
  stored_filename text,
  company text,
  tag text,
  status text not null check (status in ('Processing', 'Indexed', 'Failed')),
  storage_size text not null,
  last_updated timestamptz not null default now(),
  description text
);

create table if not exists public.document_chunks (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.documents(id) on delete cascade,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(3072) not null
);

create index if not exists document_chunks_document_id_idx on public.document_chunks(document_id);
create index if not exists documents_status_idx on public.documents(status);

drop function if exists public.match_document_chunks(extensions.vector(3072), integer);
drop function if exists public.match_document_chunks(extensions.vector(3072), integer, bigint);

create or replace function public.match_document_chunks(
  query_embedding extensions.vector(3072),
  match_count integer default 16,
  filter_document_id bigint default null
)
returns table (
  chunk_id bigint,
  document_id bigint,
  filename text,
  company text,
  tag text,
  content text,
  metadata jsonb,
  score real
)
language sql
stable
set search_path = public, extensions
as $$
  select
    chunks.id as chunk_id,
    chunks.document_id,
    documents.filename,
    documents.company,
    documents.tag,
    chunks.content,
    chunks.metadata,
    (1 - (chunks.embedding <=> query_embedding))::real as score
  from public.document_chunks as chunks
  join public.documents as documents on documents.id = chunks.document_id
  where documents.status = 'Indexed'
    and (filter_document_id is null or chunks.document_id = filter_document_id)
  order by chunks.embedding <=> query_embedding
  limit match_count;
$$;
